// <auto-generated />
using Elegance.Examples.Authentication.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elegance.Examples.Authentication.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108");

            modelBuilder.Entity("Elegance.Examples.Authentication.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_failed_count");

                    b.Property<long?>("AccessLockoutEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_lockout_end");

                    b.Property<bool>("HasMfaEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mfa");

                    b.Property<long?>("LastSignInTimestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sign_in_timestamp");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("password");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
